### ISSUE TITLE
Profiles folder takes up a lot of space

### ISSUE THREAD

**Issue by VforVolcano** [farshadz1997/Microsoft-Rewards-bot-GUI#16]
When the folders for the various profiles are generated they come to occupy as much as 5GB on the disk.
is there a way to avoid it or in case it is possible to add an option to empty it (eventually)? Or is there a need to maintain these files? 

thanks for your work

**Comment by farshadz1997** [comment]
Delete them when you need, there's nothing we can do to maintain the files

**Comment by VforVolcano** [comment]
alright I will do that. , thanks
