### ISSUE TITLE
.pyw file not doing anything

### ISSUE THREAD

**Issue by leland954** [farshadz1997/Microsoft-Rewards-bot-GUI#17]
i have pip install requirements.txt, filled in accounts.json and put the chromedriver in the same folder. And the autofarm is in my windows folder so idk how to fix this issue
![image](https://user-images.githubusercontent.com/80597725/218274960-264e7b13-3516-4f48-997c-37b8458ba581.png)

**Comment by leland954** [comment]
i looked at main.pyw in VS and when i run it, it says "No module named 'src.ui_functions'
  File "C:\Users\lelan\Downloads\Microsoft-Rewards-bot-GUI-master\main.pyw", line 1, in <module>
    from src.ui_functions import Window, QtWidgets
ModuleNotFoundError: No module named 'src.ui_functions'"

**Comment by farshadz1997** [comment]
Check is ```ui_functions.py``` exists in src or not?

**Comment by leland954** [comment]
> Check is `ui_functions.py` exists in src or not?
yes it does exist, i didnt delete any which is why im confused 
![image](https://user-images.githubusercontent.com/80597725/218279204-163057b0-85da-4824-82e9-af8f1c55c461.png)
