### ISSUE TITLE
it doesnt wanna run/dont wanna work

### ISSUE THREAD

**Issue by H4mzLDN** [farshadz1997/Microsoft-Rewards-bot-GUI#18]
i tried running it when i followed the instructions and it still doesnt want to work, pls help.

**Comment by farshadz1997** [comment]
what do you mean? app doesn't start or the start button not working?

**Comment by H4mzLDN** [comment]
app doesnt start

**Comment by farshadz1997** [comment]
Try to open it with terminal and send me the error, open CMD in Bot directory enter this command ```python main.pyw```

**Comment by leland954** [comment]
i did what u told this guy to do, its something with the src,ui,functions. I have done a fresh install of the program and still get the same issue as before. The one without the gui works fine.
![image](https://user-images.githubusercontent.com/80597725/218311791-b95729d6-5015-420b-8fd0-3f8c37ba712c.png)

**Comment by farshadz1997** [comment]
I just updated bot, get the latest version and try again.

**Comment by leland954** [comment]
> I just updated bot, get the latest version and try again.

all works now, thanks for fixing it!
