### ISSUE TITLE
Bot doesn't start, shows finish

### ISSUE THREAD

**Issue by KevinNitroG** [farshadz1997/Microsoft-Rewards-bot-GUI#20]
The bot shows that both of my account were finished. But one of mine used to be first started in US. And that account haven't been done the tasks.
And the second account is first started in Vietnam.

![image](https://user-images.githubusercontent.com/86353526/218317986-9969a255-4773-48d7-b3bd-b62e442085da.png)
![image](https://user-images.githubusercontent.com/86353526/218317997-ed6b1dc4-b503-435e-a35c-b65af2b84b4d.png)

**Comment by farshadz1997** [comment]
Try to delete log file and try again, if bot already tried to farm your accounts, then it saved them as finished in log.
