### ISSUE TITLE
Cant run it on raspberry pi 

### ISSUE THREAD

**Issue by zumokuta** [farshadz1997/Microsoft-Rewards-bot-GUI#22]
First off all, Sick code dude. Keep it up my man. Secondly When i on it on raspberry pi, it shows no internet connection in the status bar. Any solutions for this? it is connected via lan and i even tried wifi but it still comes. Thanks in advance

**Comment by farshadz1997** [comment]
I created a function to check internet connection by pinging Google, I searched and found out Raspberry Pi OS is Linux. there must be a problem with pinging. what is the output if you run this command manually: ```ping -c 1 8.8.8.8```

**Comment by zumokuta** [comment]
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=60 time=7.34 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 7.339/7.339/7.339/0.000 ms

**Comment by zumokuta** [comment]
it seems to work alright, i am able to use chrome on it so its not the wifi issue but it gives that error. https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/issues/14#issue-1599768557

**Comment by farshadz1997** [comment]
@zumokuta extract this and run it on you Raspberry Pi and send me the resuls
[get_platform.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI/files/10854421/get_platform.zip)

**Comment by zumokuta** [comment]
Linux-5.15.84-v7+-armv7l-with-glibc2.31
Linux

**Comment by farshadz1997** [comment]
@zumokuta I added a check box in global options for checking internet connection, disable it and run it again, I think this will solve your problem.

**Comment by zumokuta** [comment]
okay!

**Comment by zumokuta** [comment]
It Works! Thanks!
