### ISSUE TITLE
Add proxy settings as in the new App

### ISSUE THREAD

**Issue by JittoJoseph** [farshadz1997/Microsoft-Rewards-bot-GUI#23]
i see you have the proxy setting for every account in the V2 App, 
and also you said people who are not able to get that app to work can use the previous versions.
so could you please add the proxy settings for all accounts?
no gui needed, just could you put a feature to add a proxy with the username and password in the accounts.json

**Comment by farshadz1997** [comment]
It is already in available in terminal version, I will add proxy to this one soon.

**Comment by JittoJoseph** [comment]
oh thanks

**Comment by JittoJoseph** [comment]
btw, I could not find any information about using proxy in the terminal version's repository, and there is no proxy option in the accounts.json format example you have provided

**Comment by farshadz1997** [comment]
> btw, I could not find any information about using proxy in the terminal version's repository, and there is no proxy option in the accounts.json format example you have provided

Check the issue you created on terminal version, https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/135#issuecomment-1454867726
