### ISSUE TITLE
Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by beenruuu** [farshadz1997/Microsoft-Rewards-bot-GUI#3]
I have this problem: GTK-Message: Failed to load module "xapp-gtk3-module"

**Comment by farshadz1997** [comment]
Try these [fixes](https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module), may help you to fix your problem.

**Comment by zera4real** [comment]
@beenruuu hey, can you share your discord? I want to discuss some things.
