### ISSUE TITLE
[BUG][minor] Telegram "Earned points"

### ISSUE THREAD

**Issue by VforVolcano** [farshadz1997/Microsoft-Rewards-bot-GUI#6]
In the daily report in the "earning points" the maximum that is shown is "60" even though many more are earned ( doing a quick check with the total that is shown correctly)

![farm](https://user-images.githubusercontent.com/61471004/211573711-0a81d110-76a7-40c2-be89-16048ab4b301.png)

**Comment by farshadz1997** [comment]
does any error occurs during farm of your accounts? it resets point counter. I use and it returns the earned points correct if any there's no error during farm.

**Comment by VforVolcano** [comment]
i deleted "logs_accounts.txt" and now they are reported correctly
