### ISSUE TITLE
Add option to auto start

### ISSUE THREAD

**Issue by solutionsbysteve** [farshadz1997/Microsoft-Rewards-bot-GUI#8]
It would be nice if there was an option for the bot to auto start rather than having to click the start button. This would help for my VM which runs this script and typically do not log in to.

**Comment by FRKFFR** [comment]
if you want it to start automatically when you start your pc or at a specific time, just use the task scheduler

**Comment by solutionsbysteve** [comment]
No I am referring to the Start button within in the GUI. I already have it setup to auto start with my PC by putting in the autostart folder. However when the app launches you have to manually push the start button.

**Comment by FRKFFR** [comment]
tell the developer to do a start option with windows

**Comment by FRKFFR** [comment]
@farshadz1997 tag enhancement

**Comment by farshadz1997** [comment]
@solutionsbysteve I'll think about it, you can already do this now on terminal version.

**Comment by FRKFFR** [comment]
How

**Comment by farshadz1997** [comment]
just put farmer in Task scheduler, no input needed to run, it will run immediately.

**Comment by FRKFFR** [comment]
ok but how i can start automatically the farmer

**Comment by farshadz1997** [comment]
You don't need to do anything, just pass arguments if you want else it will do the rest with default config

**Comment by FRKFFR** [comment]
ok

**Comment by farshadz1997** [comment]
I added this option in new version of bot, try to use that one
